# Run an Experiment

Config-first workflow:

1. Pick an experiment id from `configs/experiments/`.
2. Call `run_experiment(cfg)`. That's it.

To add a new experiment, drop a YAML into `configs/experiments/` — no code change.
Every run snapshots its fully-resolved config into `data/processed/xgboost_experiments/<id>/config_snapshot.json` so results are reproducible.

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import load_config
from src.experiments.runner import run_experiment
from src.viz import make_all_plots

/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Pick one and load it. Change this single line to switch experiments.
ACTIVE = 'exp_023_gpr_xgb_ensemble'  # CHANGE THIS
cfg = load_config(ACTIVE)

print(f'Loaded: {cfg.id}')
print(f'  description : {cfg.description}')
print(f'  hypothesis  : {cfg.hypothesis}')
print(f'  sections    : {cfg.run.sections}')
print(f'  trials      : {cfg.xgb.n_trials}')
print(f'  engineered  : {cfg.features.use_engineered}')
print(f'  results dir : {cfg.results_dir}')

Loaded: exp_023_gpr_xgb_ensemble
  description : Equal-weight ensemble of the best GPR (exp_021: Matern25+Linear, ARD, 20 restarts) and XGBoost (exp_017 feature set) on reduced scope.

  hypothesis  : GPR and XGBoost make structurally different errors: GPR interpolates smoothly through kernel-distance space and captures the continuous composition-viscosity trend; XGBoost builds step-function boundaries driven by information gain and is better at fitting discrete-grid formulation effects (e.g. the sharp change at ~2 wt% C65 loading). On a 120-row dataset where neither model is large-data-asymptotically optimal, their residuals are partially uncorrelated — simple equal- weight averaging should reduce total predictive variance without introducing additional hyperparameters. GPR settings mirror exp_021 (matern25_linear, ARD, 20 restarts, per- target log1p, OHE standardisation, duplicate features removed). XGBoost uses the same feature set and per-target transforms.

  sections    : ['gpr_xgb_ensemble']
  trials      : 30
  engineered  : True
  results dir : /Users/jaidonfroggatt-morton/Documents/Warwick/Dissertation/MOTS.1/msc-dissertation-project-v2/data/processed/xgboost_experiments/exp_023_gpr_xgb_ensemble

## Run

`run_experiment` loads splits, fits physics parameters for every model, and dispatches to each section listed in `cfg.run.sections`. Each run gets a unique directory under `data/processed/xgboost_experiments/` named `{experiment_id}_{YYYYMMDD_HHMMSS}`, so re-running the same config never overwrites previous results. The path is available as `results.results_dir`.

In [3]:
results = run_experiment(cfg)

========================================================================
ACTIVE EXPERIMENT: exp_023_gpr_xgb_ensemble
========================================================================
Description : Equal-weight ensemble of the best GPR (exp_021: Matern25+Linear, ARD, 20 restarts) and XGBoost (exp_017 feature set) on reduced scope.

Hypothesis  : GPR and XGBoost make structurally different errors: GPR interpolates smoothly through kernel-distance space and captures the continuous composition-viscosity trend; XGBoost builds step-function boundaries driven by information gain and is better at fitting discrete-grid formulation effects (e.g. the sharp change at ~2 wt% C65 loading). On a 120-row dataset where neither model is large-data-asymptotically optimal, their residuals are partially uncorrelated — simple equal- weight averaging should reduce total predictive variance without introducing additional hyperparameters. GPR settings mirror exp_021 (matern25_linear, ARD, 20 restarts, per- target log1p, OHE standardisation, duplicate features removed). XGBoost uses the same feature set and per-target transforms.

Sections    : ['gpr_xgb_ensemble']
Trials      : 30
Engineered  : True
Log numeric : False
Seed        : 42

Loaded splits: train=136 rows, test=42 rows
Built physics datasets for 3 models.

======================================================================
GPR + XGBoost Ensemble  (kernel=matern25_linear, n_restarts=20, xgb_trials=30)
======================================================================

/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 8 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__sigma_0 is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

  Power Law          | k_consistency        | XGB=0.599  GPR=0.673  ENS=0.647

/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 8 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__sigma_0 is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

  Power Law          | n_flow               | XGB=0.352  GPR=0.445  ENS=0.416

/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 1 of parameter k1__k1__k2__length_scale is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 4 of parameter k1__k1__k2__length_scale is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__sigma_0 is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

  Sisko              | eta_inf_sisko        | XGB=0.030  GPR=0.108  ENS=0.131

/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 8 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__sigma_0 is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

  Sisko              | k_sisko              | XGB=0.619  GPR=0.673  ENS=0.651

/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 1 of parameter k1__k1__k2__length_scale is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 4 of parameter k1__k1__k2__length_scale is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 8 of parameter k1__k1__k2__length_scale is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__sigma_0 is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

  Sisko              | n_sisko              | XGB=0.215  GPR=0.281  ENS=0.286

/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__sigma_0 is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

  Williamson         | eta_0                | XGB=0.046  GPR=0.161  ENS=0.108

/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 5 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__sigma_0 is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

  Williamson         | eta_inf              | XGB=0.760  GPR=0.841  ENS=0.854

/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__sigma_0 is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

  Williamson         | lambda_time          | XGB=-0.201  GPR=-0.166  ENS=-0.150
  Williamson         | n_w                  | XGB=0.160  GPR=0.370  ENS=0.302

Run ID   : exp_023_gpr_xgb_ensemble_20260501_170420
Results  : /Users/jaidonfroggatt-morton/Documents/Warwick/Dissertation/MOTS.1/msc-dissertation-project-v2/data/processed/xgboost_experiments/exp_023_gpr_xgb_ensemble_20260501_170420
Duration : 55.8s

Best model (mean test R²): Power Law — R²=0.531, RMSE=17.744

/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:450: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k1__k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 4 of parameter k1__k1__k2__length_scale is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
/Users/jaidonfroggatt-morton/miniforge3/envs/msc-dissertation-mots1-v2/lib/python3.11/site-packages/sklearn/gaussian_process/kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__sigma_0 is close to the specified lower bound 0.001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

## Inspect results

`results` is an `ExperimentResults`: a dict of `SectionResult` objects keyed by section name. Every section has `model_summary`, `per_target`, and (optionally) `predictions` DataFrames.

In [4]:
for name, section in results.sections.items():
    print(f'--- {name} ---')
    display(section.sorted_by_r2().head())

print('Best (baseline/sweep/loo, first hit):', results.best())

--- gpr_xgb_ensemble ---

,variant,model_name,model_key,train_r2,train_mse,train_rmse,test_r2,test_mse,test_rmse,n_targets
0,gpr_xgb_ensemble,Power Law,power_law,0.733740,466.321935,15.290010,0.531111,624.601809,17.743549,2
1,gpr_xgb_ensemble,Sisko,sisko,0.709353,305.339516,10.198660,0.356143,420.580282,12.025156,3
2,gpr_xgb_ensemble,Williamson,williamson,0.531546,14456.372477,60.631561,0.278506,21935.643887,75.115138,4

Best (baseline/sweep/loo, first hit): None

## Plots

In [5]:
if results.results_dir is None:
    print("Run was not persisted (persist=False) — no results directory to plot into.")
else:
    saved = make_all_plots(results, results.results_dir)
    for p in saved:
        print(p)

/Users/jaidonfroggatt-morton/Documents/Warwick/Dissertation/MOTS.1/msc-dissertation-project-v2/data/processed/xgboost_experiments/exp_023_gpr_xgb_ensemble_20260501_170420/gpr_xgb_ensemble_model_comparison.png
/Users/jaidonfroggatt-morton/Documents/Warwick/Dissertation/MOTS.1/msc-dissertation-project-v2/data/processed/xgboost_experiments/exp_023_gpr_xgb_ensemble_20260501_170420/gpr_xgb_ensemble_per_target_r2_heatmap.png
/Users/jaidonfroggatt-morton/Documents/Warwick/Dissertation/MOTS.1/msc-dissertation-project-v2/data/processed/xgboost_experiments/exp_023_gpr_xgb_ensemble_20260501_170420/gpr_xgb_ensemble_train_vs_test_r2.png
/Users/jaidonfroggatt-morton/Documents/Warwick/Dissertation/MOTS.1/msc-dissertation-project-v2/data/processed/xgboost_experiments/exp_023_gpr_xgb_ensemble_20260501_170420/gpr_xgb_ensemble_variants.png

## Compare completed experiments

The `experiment_manifest.json` at the top of `data/processed/xgboost_experiments/` accumulates every run across the project.

In [6]:
import json
import pandas as pd

manifest_path = cfg.experiments_root_path / 'experiment_manifest.json'
if manifest_path.exists():
    runs = json.loads(manifest_path.read_text())['runs']
    df = pd.json_normalize(runs)
    cols = ['run_id', 'experiment_id', 'description', 'sections_run',
            'best.model_name', 'best.test_r2', 'duration_seconds', 'created_at_utc', 'notes']
    display(df[[c for c in cols if c in df.columns]])
else:
    print('No manifest yet. Run an experiment first.')

,run_id,experiment_id,description,sections_run,best.model_name,best.test_r2,duration_seconds,created_at_utc,notes
0,exp_023_gpr_xgb_ensemble_20260501_170420,exp_023_gpr_xgb_ensemble,Equal-weight ensemble of the best GPR (exp_021...,[gpr_xgb_ensemble],Power Law,0.531111,55.8,2026-05-01T17:04:20.714091+00:00,
1,exp_022_gpr_matern15_20260501_162749,exp_022_gpr_matern15,GPR kernel comparison: same fixes as exp_021 b...,[gpr_baseline],Power Law,0.557726,20.2,2026-05-01T16:27:49.983278+00:00,
2,exp_021_gpr_matern25_linear_20260501_162640,exp_021_gpr_matern25_linear,GPR with all five optimisations: duplicate fea...,[gpr_baseline],Power Law,0.558869,26.7,2026-05-01T16:26:40.092626+00:00,
3,exp_020_gpr_optimised_20260501_154521,exp_020_gpr_optimised,"Optimised GPR: ARD kernel, per-target log1p tr...",[gpr_baseline],Power Law,0.553432,13.6,2026-05-01T15:45:21.470207+00:00,
4,exp_019_gpr_log_targets_20260501_153525,exp_019_gpr_log_targets,Gaussian Process Regression baseline across al...,[gpr_baseline],Power Law,0.548718,4.1,2026-05-01T15:35:25.002784+00:00,
5,exp_018_poly_features_20260501_152640,exp_018_poly_features,SHAP-pruned features (12 retained) with degree...,[baseline],Power Law,0.373499,9.9,2026-05-01T15:26:40.499637+00:00,
6,exp_018_poly_features_20260501_152451,exp_018_poly_features,SHAP-pruned features (12 retained) with degree...,[baseline],Williamson,0.278443,10.4,2026-05-01T15:24:51.071119+00:00,"attempted without transformed targets, but the..."
7,exp_018_poly_features_20260501_152359,exp_018_poly_features,SHAP-pruned features (12 retained) with degree...,[baseline],Power Law,0.373499,9.9,2026-05-01T15:23:59.103840+00:00,
8,exp_017_shap_pruned_20260501_151827,exp_017_shap_pruned,SHAP-guided feature pruning: 10 near-zero feat...,[baseline],Power Law,0.419330,10.4,2026-05-01T15:18:27.579523+00:00,without transformed targets
9,exp_017_shap_pruned_20260501_151710,exp_017_shap_pruned,SHAP-guided feature pruning: 10 near-zero feat...,[baseline],Power Law,0.404125,9.8,2026-05-01T15:17:10.537287+00:00,with transformed targets
10,exp_017_shap_pruned_20260501_151627,exp_017_shap_pruned,SHAP-guided feature pruning: 10 near-zero feat...,[baseline],Power Law,0.404125,10.1,2026-05-01T15:16:27.301818+00:00,
11,exp_016_reduced_scope_20260501_145625,exp_016_reduced_scope,"Reduced model scope: Power Law, Sisko, William...",[baseline],Power Law,0.501829,9.7,2026-05-01T14:56:25.100187+00:00,
12,exp_015_per_target_transforms_20260501_144923,exp_015_per_target_transforms,Per-target transform selection: log1p for posi...,[baseline],Power Law,0.501829,18.5,2026-05-01T14:49:23.059361+00:00,
13,exp_015_per_target_transforms_20260501_144441,exp_015_per_target_transforms,Per-target transform selection: log1p for posi...,[baseline],Power Law,0.456368,19.3,2026-05-01T14:44:41.377145+00:00,
14,exp_005_log_target_20260501_144245,exp_005_log_target,Engineered features with log1p target transfor...,[baseline],Power Law,0.501829,18.3,2026-05-01T14:42:45.041165+00:00,
15,exp_015_per_target_transforms_20260501_144141,exp_015_per_target_transforms,Per-target transform selection: log1p for posi...,[baseline],Power Law,0.456368,19.5,2026-05-01T14:41:41.634701+00:00,
16,exp_005_log_target_20260501_142410,exp_005_log_target,Engineered features with log1p target transfor...,[baseline],Power Law,0.469473,17.2,2026-05-01T14:24:10.823079+00:00,"attempted run without engineered features, to ..."
17,exp_005_log_target_20260501_140936,exp_005_log_target,Engineered features with log1p target transfor...,[baseline],Power Law,0.501829,17.9,2026-05-01T14:09:36.246709+00:00,
18,exp_007_log_target_high_trials_20260501_140704,exp_007_log_target_high_trials,"Engineered features, log1p target transform, a...",[baseline],Power Law,0.441281,96.4,2026-05-01T14:07:04.214939+00:00,
19,exp_009_pseudo_huber_20260421_165847,exp_009_pseudo_huber,Engineered features with pseudo Huber loss obj...,[baseline],Power Law,0.379114,30.7,2026-04-21T16:58:47.068042+00:00,
20,exp_006b_high_trials_raw_20260421_161104,exp_006b_high_trials_raw,"Engineered features, 50 Optuna trials, no targ...",[baseline],Power Law,0.464674,221.7,2026-04-21T16:11:04.197287+00:00,
21,exp_008_batch_feature_20260421_160649,exp_008_batch_feature,Engineered features plus Source_Batch as an ex...,[baseline],Power Law,0.460969,78.7,2026-04-21T16:06:49.848647+00:00,
22,exp_007_log_target_high_trials_20260421_160135,exp_007_log_target_high_trials,"Engineered features, log1p target transform, a...",[baseline],Power Law,0.441281,214.2,2026-04-21T16:01:35.644568+00:00,
23,exp_006b_high_trials_raw_20260421_155434,exp_006b_high_trials_raw,"Engineered features, 50 Optuna trials, no targ...",[baseline],Power Law,0.443126,268.8,2026-04-21T15:54:34.946781+00:00,wrong config. engineered features were enabled...
24,exp_006_high_trials_20260421_154752,exp_006_high_trials,"Engineered features, 50 Optuna trials, no targ...",[baseline],Power Law,0.443126,265.9,2026-04-21T15:47:52.075140+00:00,
25,exp_005_log_target_20260421_154534,exp_005_log_target,Engineered features with log1p target transfor...,[baseline],Power Law,0.501829,30.4,2026-04-21T15:45:34.329415+00:00,
26,exp_011_loo_only_raw_20260421_152756,exp_011_loo_only_raw,Leave-one-out generalisability evaluation (row...,[loo],Power Law,0.664901,255.6,2026-04-21T15:27:56.574007+00:00,
27,exp_010_loo_only_20260421_152239,exp_010_loo_only,Leave-one-out generalisability evaluation (row...,[loo],Power Law,0.647151,264.2,2026-04-21T15:22:39.748376+00:00,
28,exp_004_trials_20_raw_20260421_145230,exp_004_trials_20_raw,Higher trials + raw features.,[baseline],Power Law,0.478763,68.5,2026-04-21T14:52:30.448196+00:00,
29,exp_003_raw_only_20260421_145112,exp_003_raw_only,Raw features only (no engineered features).,[baseline],Power Law,0.491317,30.6,2026-04-21T14:51:12.802008+00:00,
30,exp_002_trials_20_20260421_144927,exp_002_trials_20,Higher trial budget: 20 Optuna trials.,[baseline],Power Law,0.433388,70.1,2026-04-21T14:49:27.551810+00:00,
31,exp_001_baseline_20260421_144712,exp_001_baseline,"Baseline: engineered features, 10 trials.",[baseline],Power Law,0.461717,33.3,2026-04-21T14:47:12.269657+00:00,

## Annotate a run

Add a free-text note to any completed run without re-running it.
Notes are saved into the manifest and each run's `metadata.json`.

```python
from src.experiments.results import annotate_run

annotate_run(
    run_id='<paste run_id from the table above>',
    note='Your observation here — e.g. Power Law best, CY5 overfit.',
    experiments_root=cfg.experiments_root_path,
)
```

Re-run the comparison cell above to see the note in the table.

In [7]:
from src.experiments.results import annotate_run

# Replace the run_id and note, then run this cell.
annotate_run(
     run_id='exp_005_log_target_20260501_142410',
     note='attempted run without engineered features, to see if it would help with the log target. It did not.',
     experiments_root=cfg.experiments_root_path,
 )